export const AGREGA_PRODUCTO ='AGREGA_PRODUCTO';
export const AGREGA_PRODUCTO_EXITO ='AGREGA_PRODUCTO_EXITO';
export const AGREGA_PRODUCTO_ERROR ='AGREGA_PRODUCTO_ERROR';

export const COMENZAR_DESCARGA_PRODUCTO='COMENZAR_DESCARGA_PRODUCTO';
export const DESCARGA_PRODUCTO_EXITO='DESCARGA_PRODUCTO_EXITO';
export const DESCARGA_PRODUCTO_ERROR='DESCARGA_PRODUCTO_ERROR';